events {}

http {
    server {
        listen 80;

        # 역방향 터널을 거쳐 내부 (client side) Flask 서비스로 라우팅
        location / {
            proxy_pass http://tunnel-server:9000/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}
